#! /usr/bin/sh

usage () {
	echo "usage: $(basename $0) debug|release"
	exit 1
}

case $1 in
debug) ;;
release) ;;
*) usage ;;
esac

rm -rf build_$1
{
	env CC=gcc CXX=g++ meson --buildtype=$1 build_$1
	ninja -v -C build_$1
} |& tee $(basename $0)-$1.log
